catalog_name: cmo_talive
schema_name: mlops

num_features:
  - Booking_ID
  - no_of_adults
  - no_of_children
  - no_of_weekend_nights
  - no_of_week_nights
  - lead_time
  - arrival_year
  - arrival_month
  - arrival_date
  - no_of_previous_cancellations
  - no_of_previous_bookings_not_canceled
  - avg_price_per_room
  - no_of_special_requests
cat_features:
  - type_of_meal_plan
  - required_car_parking_space
  - room_type_reserved
  - market_segment_type
  - repeated_guest
target: booking_status